<a href="https://colab.research.google.com/github/medhajoshi2503/Python/blob/main/IG_PyTorchIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
torch.__version__

'2.0.1+cu118'

In [3]:
x = np.array([[1,2,4],[6,4,8],[6,6,8],[7,9,2]])

In [4]:
x

array([[1, 2, 4],
       [6, 4, 8],
       [6, 6, 8],
       [7, 9, 2]])

In [5]:
x.shape

(4, 3)

In [6]:
type(x)

numpy.ndarray

In [7]:
data = [[1,2,4],[6,4,8],[6,6,8],[7,9,2]]
x_tensor = torch.tensor(data)

In [8]:
x_tensor

tensor([[1, 2, 4],
        [6, 4, 8],
        [6, 6, 8],
        [7, 9, 2]])

In [9]:
x_tensor.size()

torch.Size([4, 3])

In [10]:
scalar = torch.tensor(5)

In [11]:
scalar

tensor(5)

In [12]:
scalar.item()

5

In [13]:
vector = torch.tensor([5,9])

In [14]:
vector

tensor([5, 9])

In [15]:
vector.shape

torch.Size([2])

In [16]:
# scalar - single number
# vector - 1D array
# matrix - 2D array
# tensor - ND array

In [17]:
torch.zeros(6)

tensor([0., 0., 0., 0., 0., 0.])

In [18]:
torch.zeros((4,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [20]:
torch.ones((4,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
torch.rand(6)

tensor([0.0498, 0.9681, 0.9986, 0.7917, 0.5357, 0.0749])

In [22]:
torch.rand((4,6))

tensor([[0.6525, 0.2319, 0.4223, 0.6302, 0.6201, 0.6315],
        [0.7665, 0.2567, 0.7845, 0.8331, 0.9811, 0.9364],
        [0.1180, 0.9985, 0.7309, 0.4698, 0.0454, 0.1472],
        [0.9264, 0.8322, 0.4989, 0.0982, 0.6362, 0.2146]])

In [23]:
x = torch.rand((4,6))

In [24]:
x.shape

torch.Size([4, 6])

In [25]:
x.dtype

torch.float32

In [26]:
x.device

device(type='cpu')

In [27]:
tensor = torch.tensor([4,7,8])

In [28]:
tensor

tensor([4, 7, 8])

In [29]:
tensor + 5

tensor([ 9, 12, 13])

In [30]:
tensor * 5

tensor([20, 35, 40])

In [31]:
tensor_2 = torch.tensor([1,2,3])

In [32]:
tensor + tensor_2

tensor([ 5,  9, 11])

In [33]:
tensor * tensor_2

tensor([ 4, 14, 24])

In [34]:
x = torch.tensor([
    [1,2,3,4],
    [5,4,6,6],
    [1,5,3,7]
])

y = torch.tensor([
    [9,21,13,14],
    [1,7,4,2],
    [1,5,3,7]
])

In [35]:
x + y

tensor([[10, 23, 16, 18],
        [ 6, 11, 10,  8],
        [ 2, 10,  6, 14]])

In [36]:
x * y

tensor([[ 9, 42, 39, 56],
        [ 5, 28, 24, 12],
        [ 1, 25,  9, 49]])

In [37]:
%%time
x @ y.T

CPU times: user 550 µs, sys: 0 ns, total: 550 µs
Wall time: 9.01 ms


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [38]:
%%time
torch.matmul(x, y.T)

CPU times: user 1.11 ms, sys: 22 µs, total: 1.14 ms
Wall time: 1.15 ms


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [39]:
%%time
torch.mm(x, y.T)

CPU times: user 200 µs, sys: 0 ns, total: 200 µs
Wall time: 1.59 ms


tensor([[146,  35,  48],
        [291,  69,  85],
        [251,  62,  84]])

In [40]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
torch.linspace(1,100,20)

tensor([  1.0000,   6.2105,  11.4211,  16.6316,  21.8421,  27.0526,  32.2632,
         37.4737,  42.6842,  47.8947,  53.1053,  58.3158,  63.5263,  68.7368,
         73.9474,  79.1579,  84.3684,  89.5789,  94.7895, 100.0000])

In [42]:
torch.randint(1,10,size=(3,4))

tensor([[3, 3, 3, 5],
        [8, 6, 3, 6],
        [6, 4, 6, 5]])

In [43]:
x = torch.randint(1,100,size=(20,))

In [44]:
x

tensor([48, 70, 24, 77, 37, 50, 24, 71,  9, 63, 24, 22, 14, 21, 48, 54, 55, 76,
        28, 58])

In [45]:
x.min()

tensor(9)

In [46]:
x.max()

tensor(77)

In [47]:
x.sum()

tensor(873)

In [48]:
x.type(torch.float32).mean()

tensor(43.6500)

In [49]:
x = torch.randint(1,50,size=(24,))

In [50]:
x.shape

torch.Size([24])

In [51]:
x.reshape(4,6)

tensor([[34, 15, 10, 27, 43,  7],
        [10,  2,  2, 21, 23, 29],
        [17, 27, 39,  5, 27, 28],
        [28, 41,  9,  2, 31, 25]])

In [52]:
x.view(6,4)

tensor([[34, 15, 10, 27],
        [43,  7, 10,  2],
        [ 2, 21, 23, 29],
        [17, 27, 39,  5],
        [27, 28, 28, 41],
        [ 9,  2, 31, 25]])

In [53]:
x = x.reshape(4,6)

In [54]:
x[0]

tensor([34, 15, 10, 27, 43,  7])

In [55]:
x[:, 0]

tensor([34, 10, 17, 28])

In [56]:
x[0:3,0:2]

tensor([[34, 15],
        [10,  2],
        [17, 27]])